kickstash/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import (
    show_main,
    create_product,
    show_xml,
    show_json,
    show_xml_by_id,
    show_json_by_id,
    register,
    login_user,
    logout_user,
    edit_product,
    delete_product,
    add_product_ajax,
    create_product_flutter
)

app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("create-product", create_product, name="create_product"),
    path("xml/", show_xml, name="show_xml"),
    path("json/", show_json, name="show_json"),
    path("xml/<str:id>/", show_xml_by_id, name="show_xml_by_id"),
    path("json/<str:id>/", show_json_by_id, name="show_json_by_id"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("edit-product/<uuid:id>", edit_product, name="edit_product"),
    path("delete-product/<uuid:id>", delete_product, name="delete_product"),
    path("create-product-ajax", add_product_ajax, name="add_product_ajax"),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.DecimalField(decimal_places=0, max_digits=15)
    description = models.TextField()
    stock = models.IntegerField(default=1)

    @property
    def is_available(self):
        return self.stock > 0

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "stock"]

    def clean_name(self):
        return strip_tags(self.cleaned_data["name"])
    
    def clean_description(self):
        return strip_tags(self.cleaned_data["description"])

main/views.py
from django.shortcuts import render, redirect, reverse
from main.forms import ProductForm
from .models import Product
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
from django.http import JsonResponse
import json


@login_required(login_url="/login")
def show_main(req):
    context = {
        # User credentials
        "name": req.user.username,
        # Cookies
        "last_login": req.COOKIES["last_login"],
        # My credentials
        "student_name": "Daffa Abhipraya Putra",
        "student_id": "2306245131",
        "student_class": "PBP D",
        # Page
        # "current_page": "main",
    }

    return render(req, "main.html", context)


def create_product(req):
    form = ProductForm(req.POST or None)

    if form.is_valid() and req.method == "POST":
        product = form.save(commit=False)
        product.user = req.user
        product.save()
        return redirect('main:show_main')

    context = {"form": form}
    return render(req, "create_product.html", context)


def show_xml(req):
    data = Product.objects.filter(user=req.user)
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_json(req):
    data = Product.objects.filter(user=req.user)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_xml_by_id(req, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_json_by_id(req, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def register(req):
    form = UserCreationForm()

    if req.method == "POST":
        form = UserCreationForm(req.POST)
        if form.is_valid():
            form.save()
            messages.success(req, "Your account has been successfully created!")
            return redirect("main:login")
    context = {"form": form}
    return render(req, "register.html", context)


def login_user(req):
    if req.method == "POST":
        form = AuthenticationForm(data=req.POST)

        if form.is_valid():
            user = form.get_user()
            login(req, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(req, "Invalid username or password. Please try again.")

    else:
        form = AuthenticationForm(req)
    context = {"form": form}
    return render(req, "login.html", context)


def logout_user(req):
    logout(req)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response


@login_required(login_url="/login")
def edit_product(req, id):
    product = Product.objects.get(pk=id)
    form = ProductForm(req.POST or None, instance=product)

    if form.is_valid() and req.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse("main:show_main"))

    context = {"form": form}
    return render(req, "edit_product.html", context)


@login_required(login_url="/login")
def delete_product(req, id):
    product = Product.objects.get(pk=id)
    product.delete()
    return HttpResponseRedirect(reverse("main:show_main"))


@csrf_exempt
@require_POST
def add_product_ajax(req):
    name = strip_tags(req.POST.get("name"))
    description = strip_tags(req.POST.get("description"))
    price = req.POST.get("price")
    stock = req.POST.get("stock")
    user = req.user

    new_product = Product(
        name=name, description=description, price=price, stock=stock, user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            stock=int(data["stock"]),
            description=data["description"],
            price=int(data["price"])
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_info.html
<!-- Not used -->

<div
	class="bg-indigo-700 rounded-xl overflow-hidden border-2 border-indigo-800"
>
	<div class="p-4 animate-shine">
		<h5 class="text-lg font-semibold text-gray-200">{{ title }}</h5>
		<p class="text-white">{{ value }}</p>
	</div>
</div>

main/templates/card_product.html
<!-- Not used -->

{% load static %} {% load custom_filters %}

<div class="text-[#cccccc] relative md:w-full shadow-md rounded-2xl break-inside-avoid flex flex-col border-t-2 border-l-2 transform hover:rotate-1 transition-transform duration-300 md:p-4 p-2 items-center space-y-3 border-[#2a2a2a] shadow-lg md:h-[34rem] lg:h-[39rem] h-[24rem] bg-gradient-to-br from-[#1f1f1f] to-[#0e0e0e]">
	<div class="w-full !aspect-square rounded-xl overflow-hidden flex items-center justify-center bg-[#262626]">
		<img src="{% static 'image/noimage.svg' %}" alt="No image available" class="w-1/4 h-1/4 object-cover rounded-lg" />
	</div>
	<div class="w-full flex flex-col space-y-2 justify-start overflow-hidden">
		<p class="md:text-xl text-lg font-semibold leading-6 text-nowrap">{{ product.name }}</p>
		<p class="md:flex hidden md:text-base text-sm">{{ product.description|truncate_words:80 }}</p>
		<p class="md:hidden md:text-base text-sm">{{ product.description|truncate_words:30 }}</p>
		<div class="flex md:flex-row md:space-x-2 flex-col space-y-2 md:items-end">
			<div class='flex flex-row space-x-2 items-center '>
				<img src="{% static 'image/star.svg' %}" alt="Rate" class="md:w-4 md:h-4 h-3 w-3" />
				<p class="md:text-sm text-xs">Unrated</p>
			</div>
			<p class="md:text-sm text-xs hidden md:flex md:items-center">∙</p>
			<p class="md:text-sm text-xs md:items-center">{{ product.stock }} stock left</p>
		</div>
	</div>
	<div class="absolute bottom-6 left-1/2 -translate-x-1/2 flex flex-row w-full items-center justify-center">
		<a href="{% url 'main:edit_product' product.pk %}" class="w-1/3 flex items-center justify-center flex-row items-center justify-center rounded-l-lg px-1 py-1 md:space-x-1 transition duration-300 bg-yellow-600 hover:bg-opacity-100 hover:text-white bg-opacity-10 text-yellow-600 border border-yellow-600">
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-pencil">
				<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />
				<path d="m15 5 4 4" />
			</svg>
			<p class="hidden md:flex">Edit</p>
		</a>
		<a href="{% url 'main:delete_product' product.pk %}" class="w-1/3 flex items-center justify-center flex-row items-center justify-center rounded-r-lg px-1 py-1 md:space-x-1 transition duration-300 bg-red-800 hover:bg-opacity-100 hover:text-white bg-opacity-20 text-red-600 border border-red-700">
			<p class="hidden md:flex">Delete</p>
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-eraser">
				<path d="m7 21-4.3-4.3c-1-1-1-2.5 0-3.4l9.6-9.6c1-1 2.5-1 3.4 0l5.6 5.6c1 1 1 2.5 0 3.4L13 21" />
				<path d="M22 21H7" />
				<path d="m5 11 9 9" />
			</svg>
		</a>
	</div>
</div>

main/templates/login.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}
<div class="min-h-screen flex items-center justify-center w-screen bg-[#0d0d0d] py-12 px-4 sm:px-6 lg:px-8 text-[#cccccc]">
	<div class="max-w-md w-full space-y-8 form-style">
		<div class="w-full items-center justify-center flex">
			<h1 class="text-5xl font-extrabold text-center relative text-white w-fit">
				<img src="{% static 'image/crown.png' %}" alt="KickStash Crown" class="absolute w-4 h-4 -top-0.5 -left-1.5 rotate-[-30deg]" />
				KickStash!
			</h1>
		</div>
		<div>
			<h2 class="mt-6 text-center text-3xl font-extrabold">Login to your account</h2>
		</div>
		<form class="mt-8 space-y-6" method="POST" action="">
			{% csrf_token %}
			<input type="hidden" name="remember" value="true" />

			<div class="rounded-md shadow-sm space-y-2">
				<div>
					<label for="username" class="mb-2 font-semibold">Username</label>
					<div class="relative mt-1">
						<input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-t-md focus:outline-none focus:ring-[#0b79f7] focus:border-[#0b79f7] sm:text-sm" placeholder="Username" />
						<div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none"></div>
					</div>
					<!-- Error handling for the username -->
					{% if form.username.errors %}
					<p class="mt-1 text-sm text-red-600">{{ form.username.errors.0 }}</p>
					{% endif %}
				</div>
				<div class="mt-4">
					<label for="password" class="mb-2 font-semibold">Password</label>
					<div class="relative mt-1">
						<input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-b-md focus:outline-none focus:ring-[#0b79f7] focus:border-[#0b79f7] sm:text-sm" placeholder="Password" />
						<div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none"></div>
					</div>
					<!-- Error handling for the password -->
					{% if form.password.errors %}
					<p class="mt-1 text-sm text-red-600">{{ form.password.errors.0 }}</p>
					{% endif %}
				</div>
			</div>

			<div>
				<button type="submit" class="group relative w-full bg-[#0b79f7] hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">Sign in</button>
			</div>
		</form>

		{% if messages %}
		<div class="mt-4">
			{% for message in messages %}
			<div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
				<span class="block sm:inline">{{ message }}</span>
			</div>
			{% endfor %}
		</div>
		{% endif %}

		<div class="text-center mt-4 text-sm flex flex-col">
			<p class="">Don't have an account yet?</p>
			<a href="{% url 'main:register' %}" class="font-medium text-[#0b79f7] hover:text-opacity-70">Register now</a>
		</div>
	</div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>KickStash!</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %} {% block content %} {% include 'navbar.html' with current_page='main' %}
<div class="overflow-x-hidden md:px-8 px-4 pt-32 min-h-screen bg-[#0d0d0d] flex flex-col w-screen space-y-12 items-center text-[#cccccc]">
	<div class="relative md:hidden">
		<h1 class="text-5xl font-extrabold text-center relative text-white">
			<img src="{% static 'image/crown.png' %}" alt="KickStash Crown" class="absolute w-4 h-4 -top-0.5 -left-1.5 rotate-[-30deg]" />
			KickStash!
		</h1>
	</div>
	<img src="{% static 'image/promo/hoka.webp' %}" alt="Weekend" class="w-full rounded-xl" />
	<div class="flex flex-col space-y-8 w-full">
		<div class="relative flex flex-row space-x-4 w-full justify-start items-center">
			<p class="font-semibold text-2xl tracking-widest text-nowrap">My Products</p>
			<div class="w-full h-0.5 bg-[#262626] w-auto flex-grow"></div>
			<div id="my-products" class="absolute -top-32"></div>
		</div>
		<div class="flex justify-start flex-row space-x-3 w-full">
			<a href="{% url 'main:create_product' %}" class="bg-[#0b79f7] hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center add-button">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-package-plus">
					<path d="M16 16h6" />
					<path d="M19 13v6" />
					<path d="M21 10V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l2-1.14" />
					<path d="m7.5 4.27 9 5.15" />
					<polyline points="3.29 7 12 12 20.71 7" />
					<line x1="12" x2="12" y1="22" y2="12" />
				</svg>
				<p>Add New Product</p>
			</a>
			<button class="bg-[#8957f6] hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#8957f6] border border-[#8957f6] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center add-button" data-modal-target="crudModal" data-modal-toggle="crudModal" onclick="showModal();">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-package-plus">
					<path d="M16 16h6" />
					<path d="M19 13v6" />
					<path d="M21 10V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l2-1.14" />
					<path d="m7.5 4.27 9 5.15" />
					<polyline points="3.29 7 12 12 20.71 7" />
					<line x1="12" x2="12" y1="22" y2="12" />
				</svg>
				<p>Add New Product (AJAX)</p>
			</button>
		</div>

		{% comment %} {% if not products %}
		<div class="w-full flex flex-col items-center justify-center space-y-2 !mb-12">
			<p>No products available.</p>
			<img src="{% static 'image/noproduct.png' %}" alt="No product" class="w-[70px]" />
		</div>
		{% else %}
		<div class="w-full grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 md:gap-6 gap-2 !mb-12">{% for product in products %} {% include 'card_product.html' with product=product %} {% endfor %}</div>
		{% endif %} {% endcomment %}

		<div id="product_cards"></div>

		<div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
			<div id="crudModalContent" class="relative bg-[#1a1a1a] rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
				<!-- Modal header -->
				<div class="flex items-center justify-between p-4 rounded-t">
					<h3 class="text-xl font-semibold">Add New Product</h3>
					<button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
						<svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
						</svg>
						<span class="sr-only">Close modal</span>
					</button>
				</div>
				<!-- Modal body -->
				<div class="px-6 py-4 space-y-6 form-style">
					<form id="productForm">
						<div class="mb-4">
							<label for="name" class="block text-sm font-medium">Name</label>
							<input type="text" id="name" name="name" class="mt-1 block w-full border rounded-md p-2 hover:border-[#0b79f7]" placeholder="Enter your product name" required />
						</div>
						<div class="mb-4">
							<label for="description" class="block text-sm font-medium">Description</label>
							<textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border rounded-md p-2 hover:border-[#0b79f7]" placeholder="Describe your product" required></textarea>
						</div>
						<div class="mb-4">
							<label for="price" class="block text-sm font-medium">Price (in IDR)</label>
							<input type="number" id="price" name="price" min="1" max="999999999999" class="mt-1 block w-full border rounded-md p-2 hover:border-[#0b79f7]" required />
						</div>
						<div class="mb-4">
							<label for="stock" class="block text-sm font-medium">Stock (minimum of 1)</label>
							<input type="number" id="stock" name="stock" min="1" max="999999999999" class="mt-1 block w-full border rounded-md p-2 hover:border-[#0b79f7]" required />
						</div>
					</form>
				</div>
				<!-- Modal footer -->
				<div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-gray-200 rounded-b justify-center md:justify-end">
					<button type="button" class="flex items-center justify-center flex-row items-center justify-center rounded-lg py-1 space-x-1 transition duration-300 hover:bg-[#cccccc] hover:text-[#262626] border border-[#cccccc] px-3" id="cancelButton">Cancel</button>
					<button type="submit" id="submitProduct" form="productForm" class="flex items-center justify-center flex-row items-center justify-center rounded-lg px-3 py-1 space-x-1 transition duration-300 bg-yellow-600 hover:bg-opacity-100 hover:text-white bg-opacity-10 text-yellow-600 border border-yellow-600">Save</button>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	function truncateDescription(description, n) {
		if (description.length <= n) {
			return description;
		}
		const truncated = description.substr(0, n);
		return truncated.substr(0, truncated.lastIndexOf(' ')) + '...';
	}

	async function getProducts() {
		return fetch("{% url 'main:show_json' %}").then((res) => res.json());
	}

	async function refreshProducts() {
		document.getElementById('product_cards').innerHTML = '';
		document.getElementById('product_cards').className = '';
		const products = await getProducts();
		let htmlString = '';
		let classNameString = '';

		if (products.length === 0) {
			classNameString = 'w-full flex flex-col items-center justify-center space-y-2 !mb-12';
			htmlString = `
				<p>No products available.</p>
				<img src="{% static 'image/noproduct.png' %}" alt="No product" class="w-[70px]" />
			`;
		} else {
			classNameString = 'w-full grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 md:gap-6 gap-2 !mb-12';
			products.forEach((item) => {
				const nameIterate = DOMPurify.sanitize(item.fields.name);
				const descriptionIterate = DOMPurify.sanitize(item.fields.description);

				htmlString += `
					<div class="text-[#cccccc] relative md:w-full shadow-md rounded-2xl break-inside-avoid flex flex-col border-t-2 border-l-2 transform hover:rotate-1 transition-transform duration-300 md:p-4 p-2 items-center space-y-3 border-[#2a2a2a] shadow-lg bg-gradient-to-br from-[#1f1f1f] to-[#0e0e0e]">
						<div class="relative w-full !aspect-square rounded-xl overflow-hidden flex items-center justify-center bg-[#262626]">
							<img src="{% static 'image/noimage.svg' %}" alt="No image available" class="w-1/4 h-1/4 object-cover rounded-lg" />
							<div class="absolute bottom-0 right-0 rounded-tl-xl bg-green-600 px-2 py-1">
								<p class="font-bold">Rp ${item.fields.price}</p>
							</div>
						</div>
						<div class="w-full flex flex-col space-y-2 justify-start overflow-hidden">
							<p class="md:text-xl text-lg font-semibold leading-6 text-nowrap">${nameIterate}</p>
							<p class="md:flex hidden md:text-base text-sm">${truncateDescription(descriptionIterate, 80)}</p>
							<p class="md:hidden md:text-base text-sm">${truncateDescription(descriptionIterate, 30)}</p>
							<div class="flex md:flex-row md:space-x-2 flex-col space-y-2 md:items-end">
								<div class='flex flex-row space-x-2 items-center '>
									<img src="{% static 'image/star.svg' %}" alt="Rate" class="md:w-4 md:h-4 h-3 w-3" />
									<p class="md:text-sm text-xs">Unrated</p>
								</div>
								<p class="md:text-sm text-xs hidden md:flex md:items-center">∙</p>
								<p class="md:text-sm text-xs md:items-center">${item.fields.stock} stock left</p>
							</div>
						</div>
						<div class="h-auto flex-grow"></div>
						<div class="flex flex-row w-full items-center justify-center">
							<a href="/edit-product/${item.pk}" class="w-1/2 flex items-center justify-center flex-row items-center justify-center rounded-l-lg px-1 py-1 md:space-x-1 transition duration-300 bg-yellow-600 hover:bg-opacity-100 hover:text-white bg-opacity-10 text-yellow-600 border border-yellow-600">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-pencil">
									<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />
									<path d="m15 5 4 4" />
								</svg>
								<p class="hidden md:flex">Edit</p>
							</a>
							<a href="/delete-product/${item.pk}" class="w-1/2 flex items-center justify-center flex-row items-center justify-center rounded-r-lg px-1 py-1 md:space-x-1 transition duration-300 bg-red-800 hover:bg-opacity-100 hover:text-white bg-opacity-20 text-red-600 border border-red-700">
								<p class="hidden md:flex">Delete</p>
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-eraser">
									<path d="m7 21-4.3-4.3c-1-1-1-2.5 0-3.4l9.6-9.6c1-1 2.5-1 3.4 0l5.6 5.6c1 1 1 2.5 0 3.4L13 21" />
									<path d="M22 21H7" />
									<path d="m5 11 9 9" />
								</svg>
							</a>
						</div>
					</div>
				`;
			});
		}
		document.getElementById('product_cards').innerHTML = htmlString;
		document.getElementById('product_cards').className = classNameString;
	}
	refreshProducts();

	const modal = document.getElementById('crudModal');
	const modalContent = document.getElementById('crudModalContent');

	function showModal() {
		const modal = document.getElementById('crudModal');
		const modalContent = document.getElementById('crudModalContent');

		modal.classList.remove('hidden');
		setTimeout(() => {
			modalContent.classList.remove('opacity-0', 'scale-95');
			modalContent.classList.add('opacity-100', 'scale-100');
		}, 50);
	}

	function hideModal() {
		const modal = document.getElementById('crudModal');
		const modalContent = document.getElementById('crudModalContent');

		modalContent.classList.remove('opacity-100', 'scale-100');
		modalContent.classList.add('opacity-0', 'scale-95');

		setTimeout(() => {
			modal.classList.add('hidden');
		}, 150);
	}

	document.getElementById('cancelButton').addEventListener('click', hideModal);
	document.getElementById('closeModalBtn').addEventListener('click', hideModal);

	function addProduct() {
		fetch("{% url 'main:add_product_ajax' %}", {
			method: 'POST',
			body: new FormData(document.querySelector('#productForm')),
		}).then((response) => refreshProducts());

		document.getElementById('productForm').reset();
		hideModal();

		return false;
	}

	document.getElementById('productForm').addEventListener('submit', (e) => {
		e.preventDefault();
		addProduct();
	});
</script>

{% include 'footer.html' with student_name=student_name student_id=student_id student_class=student_class %} {% endblock content %}